[[PDAL]]
arch = "aarch64"
git-tree-sha1 = "211dd5ee9824a5c71cbe002abc8c4fb9b0b298d4"
os = "macos"

    [[PDAL.download]]
    sha256 = "58c0570c1451ea37228f73149884f0cc0c32c9a96c71683faa60afde93b5dc15"
    url = "https://github.com/JuliaBinaryWrappers/PDAL_jll.jl/releases/download/PDAL-v2.8.2+0/PDAL.v2.8.2.aarch64-apple-darwin.tar.gz"
[[PDAL]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "bfe135add108a98f14858b170769b8c131dc1132"
libc = "glibc"
os = "linux"

    [[PDAL.download]]
    sha256 = "ce58e891ae0cadf067126ac62382a03554ce5b051e2e259bf0d0837ff1d6b1b0"
    url = "https://github.com/JuliaBinaryWrappers/PDAL_jll.jl/releases/download/PDAL-v2.8.2+0/PDAL.v2.8.2.aarch64-linux-gnu-cxx03.tar.gz"
[[PDAL]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "38adb9c523dde2cba078a9bb8080dc1f6408451d"
libc = "glibc"
os = "linux"

    [[PDAL.download]]
    sha256 = "1e80d1bbb31450f24ad2a9b79dd6343abe764a312ff9ae6716bc4340fd53135b"
    url = "https://github.com/JuliaBinaryWrappers/PDAL_jll.jl/releases/download/PDAL-v2.8.2+0/PDAL.v2.8.2.aarch64-linux-gnu-cxx11.tar.gz"
[[PDAL]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5719d92805f94867aade48091de0be7d8d742103"
libc = "musl"
os = "linux"

    [[PDAL.download]]
    sha256 = "d66bf6562cd9b458b9de9c0fd44118041b3184530fded70c046e776a70dc8896"
    url = "https://github.com/JuliaBinaryWrappers/PDAL_jll.jl/releases/download/PDAL-v2.8.2+0/PDAL.v2.8.2.aarch64-linux-musl-cxx03.tar.gz"
[[PDAL]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d928eaae3fda1ec71aa24e7df2a38df4b40f72e1"
libc = "musl"
os = "linux"

    [[PDAL.download]]
    sha256 = "8292daefed607997ae1e86c2c871adeb0e8c1530ab5edbdec87ed8fd3c4a94d4"
    url = "https://github.com/JuliaBinaryWrappers/PDAL_jll.jl/releases/download/PDAL-v2.8.2+0/PDAL.v2.8.2.aarch64-linux-musl-cxx11.tar.gz"
[[PDAL]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "0b24716b1746bcc5ec3c39ba5e08541944530abc"
libc = "glibc"
os = "linux"

    [[PDAL.download]]
    sha256 = "702fce6398247ccc90150c31bcc3de968ea84b7a7cb5cb90c5a4bca15a4bf464"
    url = "https://github.com/JuliaBinaryWrappers/PDAL_jll.jl/releases/download/PDAL-v2.8.2+0/PDAL.v2.8.2.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[PDAL]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3a737cf844316c51b08946e5367653ff63f852c0"
libc = "glibc"
os = "linux"

    [[PDAL.download]]
    sha256 = "6f54bc8a65f434f6bcbcfd44d05e22a6b0f46509e676f2334be7adc5a73a3caa"
    url = "https://github.com/JuliaBinaryWrappers/PDAL_jll.jl/releases/download/PDAL-v2.8.2+0/PDAL.v2.8.2.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[PDAL]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c6228aa2aad1efbb5666cfdf4012af1c4ade3a0a"
libc = "musl"
os = "linux"

    [[PDAL.download]]
    sha256 = "6ff7be3d814989152bfd8ddcaf525c9ab17456e14e653d4e625040e8208518ed"
    url = "https://github.com/JuliaBinaryWrappers/PDAL_jll.jl/releases/download/PDAL-v2.8.2+0/PDAL.v2.8.2.armv6l-linux-musleabihf-cxx03.tar.gz"
[[PDAL]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "504472b82994e84d83e8e55b809eec2037bb3003"
libc = "musl"
os = "linux"

    [[PDAL.download]]
    sha256 = "14777725d2d608462bc2ecaf85a6d86158fd60f45b91940e6b8b808c99f2b1fe"
    url = "https://github.com/JuliaBinaryWrappers/PDAL_jll.jl/releases/download/PDAL-v2.8.2+0/PDAL.v2.8.2.armv6l-linux-musleabihf-cxx11.tar.gz"
[[PDAL]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "385261e716068d59427970ca386fa9fbe8e2c213"
libc = "glibc"
os = "linux"

    [[PDAL.download]]
    sha256 = "0e5abdfe508494e8a95667ad923137bc03b370039ef5c058d2377c91048a2ece"
    url = "https://github.com/JuliaBinaryWrappers/PDAL_jll.jl/releases/download/PDAL-v2.8.2+0/PDAL.v2.8.2.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[PDAL]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "55f9013a7d393d57d8fa3f005d6b458fcf15fcb2"
libc = "glibc"
os = "linux"

    [[PDAL.download]]
    sha256 = "595f84bfedef6ebf670ba3887dfdd1d5b0307db3197e5ed04c5455d23942847e"
    url = "https://github.com/JuliaBinaryWrappers/PDAL_jll.jl/releases/download/PDAL-v2.8.2+0/PDAL.v2.8.2.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[PDAL]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "65443c89f93ec6c54ff1627499312f7e9a8d4ed6"
libc = "musl"
os = "linux"

    [[PDAL.download]]
    sha256 = "220cae22e541ac250a9fdc02936858f93a95e41b9eb3b2cc9212adb4350a9d24"
    url = "https://github.com/JuliaBinaryWrappers/PDAL_jll.jl/releases/download/PDAL-v2.8.2+0/PDAL.v2.8.2.armv7l-linux-musleabihf-cxx03.tar.gz"
[[PDAL]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3c020c9b758736a53d7a25210006f926c39a34cd"
libc = "musl"
os = "linux"

    [[PDAL.download]]
    sha256 = "2a7102d016fdb291b02f1b384c59c59211a0cdf53ea166c98f5d444f1f3eb6f5"
    url = "https://github.com/JuliaBinaryWrappers/PDAL_jll.jl/releases/download/PDAL-v2.8.2+0/PDAL.v2.8.2.armv7l-linux-musleabihf-cxx11.tar.gz"
[[PDAL]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "de7e934717427988cb14dff36598e3d47d90e977"
libc = "glibc"
os = "linux"

    [[PDAL.download]]
    sha256 = "ca549d8b6900aaf8fc94fae7758c5fda43005cac80f50994e7764eef3a7e06a4"
    url = "https://github.com/JuliaBinaryWrappers/PDAL_jll.jl/releases/download/PDAL-v2.8.2+0/PDAL.v2.8.2.i686-linux-gnu-cxx03.tar.gz"
[[PDAL]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "902c2d861544002fddc6145fd3a80d1c56e3aba9"
libc = "glibc"
os = "linux"

    [[PDAL.download]]
    sha256 = "ad06cf8f5e9503bb91d2f31651f6f6549281716e13b181f33ddded509f9fb47c"
    url = "https://github.com/JuliaBinaryWrappers/PDAL_jll.jl/releases/download/PDAL-v2.8.2+0/PDAL.v2.8.2.i686-linux-gnu-cxx11.tar.gz"
[[PDAL]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1dec62a81b5fbb3c1d9f1d99a188a81a4a968173"
libc = "musl"
os = "linux"

    [[PDAL.download]]
    sha256 = "648f7358704667497ac70eabf05508101b322fe18e01bb0cd76a9792804ee7f5"
    url = "https://github.com/JuliaBinaryWrappers/PDAL_jll.jl/releases/download/PDAL-v2.8.2+0/PDAL.v2.8.2.i686-linux-musl-cxx03.tar.gz"
[[PDAL]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ae0eaee5204abddcb704d9f1963e8bb9f2d03747"
libc = "musl"
os = "linux"

    [[PDAL.download]]
    sha256 = "419d3a5a4f447eae59f9e309338c1d4a7d1b05d6f224462782f46f005647ecbb"
    url = "https://github.com/JuliaBinaryWrappers/PDAL_jll.jl/releases/download/PDAL-v2.8.2+0/PDAL.v2.8.2.i686-linux-musl-cxx11.tar.gz"
[[PDAL]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "52d33a088ae35a5e3bb91c4cd44fc650545ec188"
os = "windows"

    [[PDAL.download]]
    sha256 = "fcf53162b9834cea00335e9e2b50422f79844d49b41a6c1c4fc93985fbfdfa99"
    url = "https://github.com/JuliaBinaryWrappers/PDAL_jll.jl/releases/download/PDAL-v2.8.2+0/PDAL.v2.8.2.i686-w64-mingw32-cxx03.tar.gz"
[[PDAL]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "cb42cbf8095fb018273f0da9e8b0d277a83c44e1"
os = "windows"

    [[PDAL.download]]
    sha256 = "181998d0478e9018a4951765b4e934711f79046ff5256dc6d97672b3c0b53a9a"
    url = "https://github.com/JuliaBinaryWrappers/PDAL_jll.jl/releases/download/PDAL-v2.8.2+0/PDAL.v2.8.2.i686-w64-mingw32-cxx11.tar.gz"
[[PDAL]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "86578a9e62aa05b53065c977699bdeefbfb7c9d0"
libc = "glibc"
os = "linux"

    [[PDAL.download]]
    sha256 = "addad5366c31956c2b040210c1dcf23cf6db3a7467719c1fd0e06565f33ea4d7"
    url = "https://github.com/JuliaBinaryWrappers/PDAL_jll.jl/releases/download/PDAL-v2.8.2+0/PDAL.v2.8.2.powerpc64le-linux-gnu-cxx03.tar.gz"
[[PDAL]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a87b4a0842aaf157a0fb0225bb4edad3630a87df"
libc = "glibc"
os = "linux"

    [[PDAL.download]]
    sha256 = "d2b8fb2cd082465da0bc6eb6419c9b34875569f162afe0f6eaae0eff5322adf8"
    url = "https://github.com/JuliaBinaryWrappers/PDAL_jll.jl/releases/download/PDAL-v2.8.2+0/PDAL.v2.8.2.powerpc64le-linux-gnu-cxx11.tar.gz"
[[PDAL]]
arch = "x86_64"
git-tree-sha1 = "78d2dab866be8b6e9fb9eb104fc38dd1342e43d9"
os = "macos"

    [[PDAL.download]]
    sha256 = "5219310cb0179a67890f3c1a5c03a08b25df93044e6781212083771ac663b63d"
    url = "https://github.com/JuliaBinaryWrappers/PDAL_jll.jl/releases/download/PDAL-v2.8.2+0/PDAL.v2.8.2.x86_64-apple-darwin.tar.gz"
[[PDAL]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d5c3f7089fcfc543f5502d873e19c26a36a30521"
libc = "glibc"
os = "linux"

    [[PDAL.download]]
    sha256 = "af47beb66858f971abc0e5d6c503a00b019bea56378584588bdc768e8b5261fc"
    url = "https://github.com/JuliaBinaryWrappers/PDAL_jll.jl/releases/download/PDAL-v2.8.2+0/PDAL.v2.8.2.x86_64-linux-gnu-cxx03.tar.gz"
[[PDAL]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "85bfcefebfffc2cea4fcc790f73e518e300f805b"
libc = "glibc"
os = "linux"

    [[PDAL.download]]
    sha256 = "5cc78da5d628b460a0cfcbb13c06333f970f95ca821e9d20bf50aa4a155ed154"
    url = "https://github.com/JuliaBinaryWrappers/PDAL_jll.jl/releases/download/PDAL-v2.8.2+0/PDAL.v2.8.2.x86_64-linux-gnu-cxx11.tar.gz"
[[PDAL]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e479567352ed5b73662b4aa1e6a88c45fe108296"
libc = "musl"
os = "linux"

    [[PDAL.download]]
    sha256 = "4486286a41526aef2daf526fec142c3e7cb718b18412b11483c6c5e15024cdd5"
    url = "https://github.com/JuliaBinaryWrappers/PDAL_jll.jl/releases/download/PDAL-v2.8.2+0/PDAL.v2.8.2.x86_64-linux-musl-cxx03.tar.gz"
[[PDAL]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "266a6f3703f6ad5fb66fe860e23ff71c4acaa3f5"
libc = "musl"
os = "linux"

    [[PDAL.download]]
    sha256 = "d601d6d2cd5a2dae5c8db7c359ed4bfcadea2b6352285948a282e4be0340702c"
    url = "https://github.com/JuliaBinaryWrappers/PDAL_jll.jl/releases/download/PDAL-v2.8.2+0/PDAL.v2.8.2.x86_64-linux-musl-cxx11.tar.gz"
[[PDAL]]
arch = "x86_64"
git-tree-sha1 = "a479a98f120c012484fb8a5891462a1a7ec4289f"
os = "freebsd"

    [[PDAL.download]]
    sha256 = "792dd121e626e2df83ecd347160dec92878ff8c7a6b71c3a2bf2e2df5b4a7a1e"
    url = "https://github.com/JuliaBinaryWrappers/PDAL_jll.jl/releases/download/PDAL-v2.8.2+0/PDAL.v2.8.2.x86_64-unknown-freebsd.tar.gz"
[[PDAL]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "709a664560a996ea3c4c00b53d12d3581e6ae5e7"
os = "windows"

    [[PDAL.download]]
    sha256 = "f3f2489d6f444c3ab83366430aa5df69dbaf68af0794eb58d2f76b8f4485ddea"
    url = "https://github.com/JuliaBinaryWrappers/PDAL_jll.jl/releases/download/PDAL-v2.8.2+0/PDAL.v2.8.2.x86_64-w64-mingw32-cxx03.tar.gz"
[[PDAL]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7187100a49ecba26fb8a11bf0592de479719731d"
os = "windows"

    [[PDAL.download]]
    sha256 = "bbdb74abdc3926bbe2045456fe81fb9cfdb69c83b226d8c591904707e3e1907d"
    url = "https://github.com/JuliaBinaryWrappers/PDAL_jll.jl/releases/download/PDAL-v2.8.2+0/PDAL.v2.8.2.x86_64-w64-mingw32-cxx11.tar.gz"
