[[PDAL]]
arch = "aarch64"
git-tree-sha1 = "859b59e0f23bcd795e33ad24120c5302287a1aa9"
os = "macos"

    [[PDAL.download]]
    sha256 = "4c0851414cd20dc87f158e00d99ce8235732da71282fe2b2da18a74b4fe8054b"
    url = "https://github.com/JuliaBinaryWrappers/PDAL_jll.jl/releases/download/PDAL-v2.9.0+0/PDAL.v2.9.0.aarch64-apple-darwin.tar.gz"
[[PDAL]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "add9bac2cc56a931e1ec57e10c23784583a5f6d2"
libc = "glibc"
os = "linux"

    [[PDAL.download]]
    sha256 = "8f31548b81ff611647a41ffbe409b8e6d94a82a807dfde0e2625680eb7ed495d"
    url = "https://github.com/JuliaBinaryWrappers/PDAL_jll.jl/releases/download/PDAL-v2.9.0+0/PDAL.v2.9.0.aarch64-linux-gnu-cxx03.tar.gz"
[[PDAL]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5eec308f37fbb789d019d00e5e163589f8740f2d"
libc = "glibc"
os = "linux"

    [[PDAL.download]]
    sha256 = "a167c0817b018c0fc0420eb0a641d117226f252819ba8e3b5a72e0c4ca03c282"
    url = "https://github.com/JuliaBinaryWrappers/PDAL_jll.jl/releases/download/PDAL-v2.9.0+0/PDAL.v2.9.0.aarch64-linux-gnu-cxx11.tar.gz"
[[PDAL]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "7f104f1c7107857042976d75dd86085f621ff018"
libc = "musl"
os = "linux"

    [[PDAL.download]]
    sha256 = "42d791cfb855a4cd2748c35f21172643c170fb19e2be690373d7ee2dfb081c73"
    url = "https://github.com/JuliaBinaryWrappers/PDAL_jll.jl/releases/download/PDAL-v2.9.0+0/PDAL.v2.9.0.aarch64-linux-musl-cxx03.tar.gz"
[[PDAL]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e64946b09aa4d7e989f0098472eeb0a19250373f"
libc = "musl"
os = "linux"

    [[PDAL.download]]
    sha256 = "c5672a1fe8200226d09594761e412a63e1dae86b8a1f7b02ea259dd83f9e7a1a"
    url = "https://github.com/JuliaBinaryWrappers/PDAL_jll.jl/releases/download/PDAL-v2.9.0+0/PDAL.v2.9.0.aarch64-linux-musl-cxx11.tar.gz"
[[PDAL]]
arch = "aarch64"
git-tree-sha1 = "f0903a7cbb2596a4d85e40216e73c126b4c54c2f"
os = "freebsd"

    [[PDAL.download]]
    sha256 = "8e2efab873b7978b3e58e0ff6a4b451b8b4666bda307cfcbc67cf7d22c8edfe0"
    url = "https://github.com/JuliaBinaryWrappers/PDAL_jll.jl/releases/download/PDAL-v2.9.0+0/PDAL.v2.9.0.aarch64-unknown-freebsd.tar.gz"
[[PDAL]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c86989b3f79df2c956c27c001e6eb9e2d50c6f75"
libc = "glibc"
os = "linux"

    [[PDAL.download]]
    sha256 = "6c28a52e9b88902ac9ddce074f0d4c91e547485b0c4bef2f2026426e07070f04"
    url = "https://github.com/JuliaBinaryWrappers/PDAL_jll.jl/releases/download/PDAL-v2.9.0+0/PDAL.v2.9.0.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[PDAL]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "21af99d4dbcee45f2516f4e17f6e680f2c09fbf2"
libc = "glibc"
os = "linux"

    [[PDAL.download]]
    sha256 = "581caebb8355682a5ffb9bd283fea231b75c789bc07e101daf835f240663e865"
    url = "https://github.com/JuliaBinaryWrappers/PDAL_jll.jl/releases/download/PDAL-v2.9.0+0/PDAL.v2.9.0.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[PDAL]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "cb941e847adb28abdb3c33debdade437bca557e1"
libc = "musl"
os = "linux"

    [[PDAL.download]]
    sha256 = "87323a8f4f01c413115bb3312cc6cf19bbd3788e646e9b212b5606b30bada970"
    url = "https://github.com/JuliaBinaryWrappers/PDAL_jll.jl/releases/download/PDAL-v2.9.0+0/PDAL.v2.9.0.armv6l-linux-musleabihf-cxx03.tar.gz"
[[PDAL]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "18ca5b2554a9b9704afeeff2feeb14801d84d1c6"
libc = "musl"
os = "linux"

    [[PDAL.download]]
    sha256 = "1207859908b8b6e526796c882c6c2c21bb3d2cb920373084f9fdea2f5ea47d10"
    url = "https://github.com/JuliaBinaryWrappers/PDAL_jll.jl/releases/download/PDAL-v2.9.0+0/PDAL.v2.9.0.armv6l-linux-musleabihf-cxx11.tar.gz"
[[PDAL]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "299c807677ab3db11c721320e525eeced4305b65"
libc = "glibc"
os = "linux"

    [[PDAL.download]]
    sha256 = "116bce32cc64d690b868390c7696217903c02a1008cab47773207327d483d72f"
    url = "https://github.com/JuliaBinaryWrappers/PDAL_jll.jl/releases/download/PDAL-v2.9.0+0/PDAL.v2.9.0.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[PDAL]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "035062dc96fee1cfeb0db27960b4a09aab90fb4d"
libc = "glibc"
os = "linux"

    [[PDAL.download]]
    sha256 = "a10eca1be6ae01e90ae97d8106d2c881a11e1dcabf875c64df7e2fdee4511e21"
    url = "https://github.com/JuliaBinaryWrappers/PDAL_jll.jl/releases/download/PDAL-v2.9.0+0/PDAL.v2.9.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[PDAL]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "650664d4c0a6442203b1bb0e670fb18d11f9bc16"
libc = "musl"
os = "linux"

    [[PDAL.download]]
    sha256 = "00ebbb0a83cfe644282fc70c34c88ac3c9b62b76fa717ee34edd1a246c16f226"
    url = "https://github.com/JuliaBinaryWrappers/PDAL_jll.jl/releases/download/PDAL-v2.9.0+0/PDAL.v2.9.0.armv7l-linux-musleabihf-cxx03.tar.gz"
[[PDAL]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "06dc778f36bee0986e649622bcd01aab64d02cd4"
libc = "musl"
os = "linux"

    [[PDAL.download]]
    sha256 = "7c95cb407f5dbf0b66a24808a0e06104611778d300614a10157e9213d671ba02"
    url = "https://github.com/JuliaBinaryWrappers/PDAL_jll.jl/releases/download/PDAL-v2.9.0+0/PDAL.v2.9.0.armv7l-linux-musleabihf-cxx11.tar.gz"
[[PDAL]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f593ebcea04a214dc9a289853998dfe2e5d3aa09"
libc = "glibc"
os = "linux"

    [[PDAL.download]]
    sha256 = "0c7f3bab3abc4fef95d278535dd010c6e34193ef47f0fd7ba8947aee1c203bb7"
    url = "https://github.com/JuliaBinaryWrappers/PDAL_jll.jl/releases/download/PDAL-v2.9.0+0/PDAL.v2.9.0.i686-linux-gnu-cxx03.tar.gz"
[[PDAL]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "90d5f2032f2801deb5ff15c3102077d8299bd62f"
libc = "glibc"
os = "linux"

    [[PDAL.download]]
    sha256 = "557a59b5622a843131382d6ba57b401b0aafd47d1d09af599b804cbdf158223a"
    url = "https://github.com/JuliaBinaryWrappers/PDAL_jll.jl/releases/download/PDAL-v2.9.0+0/PDAL.v2.9.0.i686-linux-gnu-cxx11.tar.gz"
[[PDAL]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f305f2aed38930ce28cb8846d64f04c41cc0e723"
libc = "musl"
os = "linux"

    [[PDAL.download]]
    sha256 = "89cec9b4622854531063f1046135ae2405294c69cccdb6654b0b4ec24cc74d96"
    url = "https://github.com/JuliaBinaryWrappers/PDAL_jll.jl/releases/download/PDAL-v2.9.0+0/PDAL.v2.9.0.i686-linux-musl-cxx03.tar.gz"
[[PDAL]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "daf6228d74283c21e229d4d994a1877ac6f61a46"
libc = "musl"
os = "linux"

    [[PDAL.download]]
    sha256 = "60ad0df168d5ccfc741d0bc72ccac7906cca6d88b7ae1c88558d597bcb6c9d00"
    url = "https://github.com/JuliaBinaryWrappers/PDAL_jll.jl/releases/download/PDAL-v2.9.0+0/PDAL.v2.9.0.i686-linux-musl-cxx11.tar.gz"
[[PDAL]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "230dd4bb1066ac28f439ee93750db5e08d969d0c"
os = "windows"

    [[PDAL.download]]
    sha256 = "ed4a8d7b14e74ec67619df73fe87c292bb3c11ed3a6c5ae79650c2105767e2c5"
    url = "https://github.com/JuliaBinaryWrappers/PDAL_jll.jl/releases/download/PDAL-v2.9.0+0/PDAL.v2.9.0.i686-w64-mingw32-cxx03.tar.gz"
[[PDAL]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9d0265b04a654f718782c6ea919d6b43fefa8b69"
os = "windows"

    [[PDAL.download]]
    sha256 = "6708997a3cb062cfb3118ffa8b5539f6e39826078f1354569e4d53234adc099d"
    url = "https://github.com/JuliaBinaryWrappers/PDAL_jll.jl/releases/download/PDAL-v2.9.0+0/PDAL.v2.9.0.i686-w64-mingw32-cxx11.tar.gz"
[[PDAL]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a0f952cbefd6de6621c800daa45913c63b2ff2e9"
libc = "glibc"
os = "linux"

    [[PDAL.download]]
    sha256 = "7892a383d5cfdd0799c267e87f6d97a1f83a1396ea70657198b047ed47a9b8c3"
    url = "https://github.com/JuliaBinaryWrappers/PDAL_jll.jl/releases/download/PDAL-v2.9.0+0/PDAL.v2.9.0.powerpc64le-linux-gnu-cxx03.tar.gz"
[[PDAL]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "bfcdf83cf3ddec262e58eeedc690c5be537e313f"
libc = "glibc"
os = "linux"

    [[PDAL.download]]
    sha256 = "bf940aca59b363715b0e1c31b76a5ed2d6b5d420a2d89410df822ed99f1206b2"
    url = "https://github.com/JuliaBinaryWrappers/PDAL_jll.jl/releases/download/PDAL-v2.9.0+0/PDAL.v2.9.0.powerpc64le-linux-gnu-cxx11.tar.gz"
[[PDAL]]
arch = "riscv64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9f74cb694c05447fbe93743ed6378f051fe8dac2"
libc = "glibc"
os = "linux"

    [[PDAL.download]]
    sha256 = "2328510e83c910a814b13a4179e08e95f5b478d033946862d2744dfc942fcc25"
    url = "https://github.com/JuliaBinaryWrappers/PDAL_jll.jl/releases/download/PDAL-v2.9.0+0/PDAL.v2.9.0.riscv64-linux-gnu-cxx03.tar.gz"
[[PDAL]]
arch = "riscv64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "98736e51c9c115d581d9faafad1af6b2eb81e8c6"
libc = "glibc"
os = "linux"

    [[PDAL.download]]
    sha256 = "ff7ebf644efab8a029fb2fe7e96841d3b1e5c80d196646c612ab2593365bb16c"
    url = "https://github.com/JuliaBinaryWrappers/PDAL_jll.jl/releases/download/PDAL-v2.9.0+0/PDAL.v2.9.0.riscv64-linux-gnu-cxx11.tar.gz"
[[PDAL]]
arch = "x86_64"
git-tree-sha1 = "da474475497717d57cfdea93b14f29cb233dda7c"
os = "macos"

    [[PDAL.download]]
    sha256 = "6b94fc325f43bd3da69cdc9cb9bf37feda961f6dd42b747a611e6afd3455e97e"
    url = "https://github.com/JuliaBinaryWrappers/PDAL_jll.jl/releases/download/PDAL-v2.9.0+0/PDAL.v2.9.0.x86_64-apple-darwin.tar.gz"
[[PDAL]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "727fb3f6b12106b113ae30390f25adfb5c442b57"
libc = "glibc"
os = "linux"

    [[PDAL.download]]
    sha256 = "7eab0a55c139d28abf9ca79182c7150693cb7ce41025ed344c230ae131c39ef3"
    url = "https://github.com/JuliaBinaryWrappers/PDAL_jll.jl/releases/download/PDAL-v2.9.0+0/PDAL.v2.9.0.x86_64-linux-gnu-cxx03.tar.gz"
[[PDAL]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "75a2ad1eb73816a8c57fe474c76b857a4ac09e9e"
libc = "glibc"
os = "linux"

    [[PDAL.download]]
    sha256 = "5522ca2654697100e57f1fdda7d9f2394e45411162f2f433175843c000b2f492"
    url = "https://github.com/JuliaBinaryWrappers/PDAL_jll.jl/releases/download/PDAL-v2.9.0+0/PDAL.v2.9.0.x86_64-linux-gnu-cxx11.tar.gz"
[[PDAL]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c175d61283ec9e84b453486d92dfee27d0aa1b9a"
libc = "musl"
os = "linux"

    [[PDAL.download]]
    sha256 = "2593f2f1c07c7a04565cc236e6f71f6d958390c8cc4e2b7a6b13e46fa07aa0a8"
    url = "https://github.com/JuliaBinaryWrappers/PDAL_jll.jl/releases/download/PDAL-v2.9.0+0/PDAL.v2.9.0.x86_64-linux-musl-cxx03.tar.gz"
[[PDAL]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "68fafb892ecdd98d7c866cb2746f84a34f52c872"
libc = "musl"
os = "linux"

    [[PDAL.download]]
    sha256 = "1ddea5eab980abbd48aa884100da99e8a97ff77a5ed74702c08cd1ca4014399e"
    url = "https://github.com/JuliaBinaryWrappers/PDAL_jll.jl/releases/download/PDAL-v2.9.0+0/PDAL.v2.9.0.x86_64-linux-musl-cxx11.tar.gz"
[[PDAL]]
arch = "x86_64"
git-tree-sha1 = "abe61cdfb18e1661de11642abce4c83416f81b3e"
os = "freebsd"

    [[PDAL.download]]
    sha256 = "da792092c85a26b2a03c338c193f7cb8fe4f087d9ac18b68ee8b653fd5ce6d3c"
    url = "https://github.com/JuliaBinaryWrappers/PDAL_jll.jl/releases/download/PDAL-v2.9.0+0/PDAL.v2.9.0.x86_64-unknown-freebsd.tar.gz"
[[PDAL]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d92ed041f070e17a4bd9516f8e6f40873beac5b3"
os = "windows"

    [[PDAL.download]]
    sha256 = "3a1913eb1e946a8f35ffcf261cd6d06e998ca4611e9a5ebbe3f759f6a0379828"
    url = "https://github.com/JuliaBinaryWrappers/PDAL_jll.jl/releases/download/PDAL-v2.9.0+0/PDAL.v2.9.0.x86_64-w64-mingw32-cxx03.tar.gz"
[[PDAL]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3c56c3592c855d3bdced4e537f770f2a523f0237"
os = "windows"

    [[PDAL.download]]
    sha256 = "b908b9cbed8dad16bb75e09c7d948c77b7e16257c1c76db4f5bb4127c45c932e"
    url = "https://github.com/JuliaBinaryWrappers/PDAL_jll.jl/releases/download/PDAL-v2.9.0+0/PDAL.v2.9.0.x86_64-w64-mingw32-cxx11.tar.gz"
