# Autogenerated wrapper script for PDAL_jll for i686-w64-mingw32-cxx03
export libpdal_base, libpdal_plugin_kernel_fauxplugin, libpdal_util, pdal

using GDAL_jll
using libgeotiff_jll
using LASzip_jll
JLLWrappers.@generate_wrapper_header("PDAL")
JLLWrappers.@declare_library_product(libpdal_base, "libpdalcpp.dll")
JLLWrappers.@declare_library_product(libpdal_plugin_kernel_fauxplugin, "libpdal_plugin_kernel_fauxplugin.dll")
JLLWrappers.@declare_library_product(libpdal_util, "libpdal_util.dll")
JLLWrappers.@declare_executable_product(pdal)
function __init__()
    JLLWrappers.@generate_init_header(GDAL_jll, libgeotiff_jll, LASzip_jll)
    JLLWrappers.@init_library_product(
        libpdal_base,
        "bin\\libpdalcpp.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libpdal_plugin_kernel_fauxplugin,
        "bin\\libpdal_plugin_kernel_fauxplugin.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libpdal_util,
        "bin\\libpdal_util.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_executable_product(
        pdal,
        "bin\\pdal.exe",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
